### ISSUE TITLE
Communicate data between HPS and Nios using mailbox

### ISSUE THREAD

**Issue by nuraalkhateeb** [sahandKashani/SoC-FPGA-Design-Guide#7]
Hi Sahand,

I was wondering, have you used the altera avalon mailbox simple core in the past to communicate data between the HPS and Nios side?

Thanks

**Comment by sahandKashani** [comment]
Not between the HPS and the Nios, but only between 2 Nios processors. I'm not sure, but if I recall correctly the mailbox core does not pass data, but rather pointers. I'm not sure how it would behave if you use a HPS and a Nios processor, since the pointers would not correspond to the same address space.

**Comment by nuraalkhateeb** [comment]
I did see an altera powerpoint online called "Building Multi-Proccessor FPGA Systems" where they were using mmap to map the physical address of the mailbox to virtual memory. 

![capture](https://cloud.githubusercontent.com/assets/10977500/22253690/8d921e4a-e220-11e6-8a70-d3bc34c56c24.PNG)

I probably have to take this approach then instead of using the altera avalon mailbox simple core.

**Comment by sahandKashani** [comment]
You can also just use a mutex to control access to some shared memory that both CPUs have access to.

**Comment by nuraalkhateeb** [comment]
Thanks Sahand. I'll look into using a mutex as well.
