### ISSUE TITLE
bridge enable vs run bridge_enable_handoff 

### ISSUE THREAD

**Issue by nuraalkhateeb** [sahandKashani/SoC-FPGA-Design-Guide#9]
Sahand,

I was wondering why bridge enable was used in the u-boot.script over using run bridge_enable_handoff?

Thanks Sahand

**Comment by sahandKashani** [comment]
From what I remember, `bridge_enable_handoff` is not available in the official u-boot repositories. It is a custom instruction defined by the altera port of the bootloader, but since I am using the official U-boot from denx, I had to use what was available there. I prefer using standard methods rather than custom ones which are not portable/maintainable.

**Comment by nuraalkhateeb** [comment]
Understandable, so really the two should be the same correct?

**Comment by sahandKashani** [comment]
I'm guessing so. If I recall correctly, I printed out all the commands and environment variables present in the official and altera versions of U-Boot, and that's how I identified the command.

That being said, `bridge_enable` is only available in fairly recent versions of U-Boot (like the one I used in the tutorial), but is present in earlier versions of the altera port.
